CREATE DATABASE IF NOT EXISTS shorturl;
USE shorturl;

CREATE TABLE IF NOT EXISTS tbl_shorturl
(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    real_url VARCHAR(255) UNIQUE,
    short_url VARCHAR(255) UNIQUE,
    count INT DEFAULT 0,
    ctime DATETIME
)ENGINE=INNODB;
